In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/laptop-data/laptop_data.xlsx


In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_excel(r"/kaggle/input/laptop-data/laptop_data.xlsx")

In [4]:
df.head()

Bellek Hızı Cihaz Ağırlığı Ekran Boyutu Ekran Kartı Bellek Tipi  \
0    1066 MHz            NaN       10 inç                     NaN   
1    1066 MHz            NaN       10 inç                     NaN   
2    1066 MHz            NaN       10 inç                     NaN   
3    3200 MHz       1 - 2 kg     15,6 inç                   GDDR4   
4    3200 MHz       1 - 2 kg     15,6 inç                   GDDR5   

  Ekran Kartı Hafızası    Ekran Kartı Tipi Ekran Panel Tipi İşlemci Nesli  \
0                 1 GB                 NaN              IPS       1.Nesil   
1                 1 GB                 NaN              IPS       1.Nesil   
2                 1 GB                 NaN              IPS       1.Nesil   
3                 2 GB  Harici Ekran Kartı              LED     10. Nesil   
4                 2 GB  Harici Ekran Kartı              LED     10. Nesil   

  İşlemci  İşletim Sistemi Kart Okuyucu  Aydınlatma Maksimum İşlemci Hızı  \
0   1000M          Android          NaN           0              1,05 GHz   
1   1000M          Android          NaN           0              1,05 GHz   
2   1000M          Android          NaN           0              1,05 GHz   
3  1035G1  Windows 10 Home          Var           0               3,6 GHz   
4  1035G1  Windows 10 Home          Yok           0               3,6 GHz   

  Max Ekran Çözünürlüğü Parmak İzi Okuyucu Ram (Sistem Belleği)  \
0                   NaN                NaN                  NaN   
1                   NaN                NaN                  NaN   
2                   NaN                NaN                  NaN   
3           1920 x 1080                Yok                 8 GB   
4           1920 x 1080                Yok                12 GB   

  SSD Kapasitesi Ürün Modeli       Fiyat  
0           1 TB    Notebook  Çok Yüksek  
1           1 TB    Notebook  Çok Yüksek  
2           1 TB    Notebook        Orta  
3         512 GB    Notebook       Düşük  
4           1 TB    Notebook       Düşük

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Bellek Hızı              888 non-null    object
 1   Cihaz Ağırlığı           985 non-null    object
 2   Ekran Boyutu             994 non-null    object
 3   Ekran Kartı Bellek Tipi  884 non-null    object
 4   Ekran Kartı Hafızası     946 non-null    object
 5   Ekran Kartı Tipi         955 non-null    object
 6   Ekran Panel Tipi         994 non-null    object
 7   İşlemci Nesli            946 non-null    object
 8   İşlemci                  979 non-null    object
 9   İşletim Sistemi          994 non-null    object
 10  Kart Okuyucu             864 non-null    object
 11  Aydınlatma               994 non-null    int64 
 12  Maksimum İşlemci Hızı    950 non-null    object
 13  Max Ekran Çözünürlüğü    988 non-null    object
 14  Parmak İzi Okuyucu       886 non-null    o

In [6]:
df["Fiyat"].unique()

array(['Çok Yüksek', 'Orta', 'Düşük', 'Çok Düşük', 'Yüksek'], dtype=object)

In [7]:
for col in df.columns:
    print(df[col].value_counts())

Bellek Hızı
3200 MHz    655
4800 MHz    100
2666 MHz     71
2400 MHz     17
2933 MHz     14
5200 MHz      6
4266 MHz      6
4267 MHz      4
1066 MHz      3
3000 MHz      3
3733 MHz      2
5500 MHz      2
2133 MHz      2
6400 MHz      1
1600 MHz      1
1866 MHz      1
Name: count, dtype: int64
Cihaz Ağırlığı
1 - 2 kg        586
2 - 4 kg        303
2 kg ve Altı     95
4 kg ve Üstü      1
Name: count, dtype: int64
Ekran Boyutu
15,6 inç    681
14 inç      136
16 inç       38
17,3 inç     36
16,1 inç     30
14,1 inç     20
13 inç       20
13,3 inç     15
10 inç        3
18,4 inç      3
15 inç        2
18 inç        2
17 inç        2
11,6 inç      2
13,5 inç      2
12,3 inç      1
13,4 inç      1
Name: count, dtype: int64
Ekran Kartı Bellek Tipi
Onboard    529
GDDR6      289
GDDR5       45
GDDR4       12
DDR5         7
DDR3         1
GDDR6X       1
Name: count, dtype: int64
Ekran Kartı Hafızası
Paylaşımlı    597
4 GB          142
2 GB           82
6 GB           72
8 GB           37
16 GB   

In [8]:
df["Ram (Sistem Belleği)"].unique()

array([nan, '8 GB', '12 GB', '16 GB', '32 GB', '4 GB', '20 GB', '24 GB',
       '40 GB', '36 GB', '64 GB', '8\xa0GB', '128 GB'], dtype=object)

In [9]:
df.isnull().sum()

Bellek Hızı                106
Cihaz Ağırlığı               9
Ekran Boyutu                 0
Ekran Kartı Bellek Tipi    110
Ekran Kartı Hafızası        48
Ekran Kartı Tipi            39
Ekran Panel Tipi             0
İşlemci Nesli               48
İşlemci                     15
İşletim Sistemi              0
Kart Okuyucu               130
Aydınlatma                   0
Maksimum İşlemci Hızı       44
Max Ekran Çözünürlüğü        6
Parmak İzi Okuyucu         108
Ram (Sistem Belleği)         7
SSD Kapasitesi               3
Ürün Modeli                  0
Fiyat                        0
dtype: int64

In [10]:
df["Ram (Sistem Belleği)"].fillna(df["Ram (Sistem Belleği)"].mode()[0] , inplace = True)

In [11]:
df["Ram (Sistem Belleği)"].isnull().sum()

np.int64(0)

In [12]:
df["Ram (Sistem Belleği)"].unique()

array(['16 GB', '8 GB', '12 GB', '32 GB', '4 GB', '20 GB', '24 GB',
       '40 GB', '36 GB', '64 GB', '8\xa0GB', '128 GB'], dtype=object)

In [13]:
df["Ram (Sistem Belleği)"] = df["Ram (Sistem Belleği)"].str.replace("8\xa0GB" , "80 GB")

In [14]:
df["Ram (Sistem Belleği)"].unique()

array(['16 GB', '8 GB', '12 GB', '32 GB', '4 GB', '20 GB', '24 GB',
       '40 GB', '36 GB', '64 GB', '80 GB', '128 GB'], dtype=object)

In [15]:
df['Ram (Sistem Belleği)'] = df['Ram (Sistem Belleği)'].str.replace(' GB', '', regex=False).astype(int)

In [16]:
df["Ram (Sistem Belleği)"].unique()

array([ 16,   8,  12,  32,   4,  20,  24,  40,  36,  64,  80, 128])

In [17]:
df["SSD Kapasitesi"].fillna(df["SSD Kapasitesi"].mode()[0], inplace = True) # mode degeriyle nan valueları doldur

In [18]:
df["SSD Kapasitesi"].unique()

array(['1 TB', '512 GB', '256 GB', '128 GB', '120 GB', '500 GB', '4 TB',
       '0 GB', '250 GB', '2 TB', ' 0 GB', '64 GB'], dtype=object)

In [19]:
df["SSD Kapasitesi"] = df["SSD Kapasitesi"].str.strip() # gereksiz bosluklardan kurtul

In [20]:
df["SSD Kapasitesi"].unique()

array(['1 TB', '512 GB', '256 GB', '128 GB', '120 GB', '500 GB', '4 TB',
       '0 GB', '250 GB', '2 TB', '64 GB'], dtype=object)

In [21]:
df["SSD Kapasitesi"].isnull().sum()

np.int64(0)

In [22]:
df["SSD Kapasitesi"] = df["SSD Kapasitesi"].str.replace(" GB", "", regex = False)

In [23]:
df["SSD Kapasitesi"].unique()

array(['1 TB', '512', '256', '128', '120', '500', '4 TB', '0', '250',
       '2 TB', '64'], dtype=object)

In [24]:
def convert_storage_to_gb(value):
    # Eğer değer NaN (boş) ise doğrudan döndür
    if pd.isna(value):
        return np.nan
    
    # Küçük harfe çevir ve boşlukları temizle
    value = str(value).lower().strip()
    
    # Sayısal kısmı ayıkla (regex ile)
    import re
    number_match = re.search(r'(\d+)', value)
    if not number_match:
        return np.nan
    
    number = int(number_match.group(1))
    
    # Birim kontrolü ve dönüşüm
    if 'tb' in value:
        return number * 1024
    else:
        # GB veya birim belirtilmemişse direkt sayıyı döndür
        return number

In [25]:
df['SSD Kapasitesi'] = df['SSD Kapasitesi'].apply(convert_storage_to_gb).astype(int)

In [26]:
df["SSD Kapasitesi"].unique()

array([1024,  512,  256,  128,  120,  500, 4096,    0,  250, 2048,   64])

In [27]:
df["Ekran Kartı Hafızası"].unique()

array(['1 GB', '2 GB', '4 GB', '8 GB', 'Paylaşımlı', '6 GB', nan, '12 GB',
       '16 GB'], dtype=object)

In [28]:
df["Ekran Kartı Hafızası"] = df["Ekran Kartı Hafızası"].str.replace("Paylaşımlı", "0").str.replace(" GB", "")

In [29]:
df["Ekran Kartı Hafızası"].unique()

array(['1', '2', '4', '8', '0', '6', nan, '12', '16'], dtype=object)

In [30]:
df["Ekran Kartı Hafızası"].fillna(df["Ekran Kartı Hafızası"].mode()[0], inplace = True)

In [31]:
df["Ekran Kartı Hafızası"].unique()

array(['1', '2', '4', '8', '0', '6', '12', '16'], dtype=object)

In [32]:
df["Ekran Kartı Hafızası"].isnull().sum()

np.int64(0)

In [33]:
df["Cihaz Ağırlığı"].unique()

array([nan, '1 - 2 kg', '2 - 4 kg', '2 kg ve Altı', '4 kg ve Üstü'],
      dtype=object)

In [34]:
agirlik_map = {
    '2 kg ve Altı': 1,
    '1 - 2 kg': 1.5,
    '2 - 4 kg': 3,
    '4 kg ve Üstü': 5,
    np.nan: 1.5 # Boş değerleri mod değerle doldurabiliriz
}

In [35]:
df["Cihaz Ağırlığı"].mode()[0]

'1 - 2 kg'

In [36]:
df["Cihaz Ağırlığı"] = df["Cihaz Ağırlığı"].map(agirlik_map)

In [37]:
df["Cihaz Ağırlığı"].unique()

array([1.5, 3. , 1. , 5. ])

In [38]:
df["Ekran Boyutu"].unique()

array(['10 inç', '15,6 inç', '13,3 inç', '14 inç', '17,3 inç', '13 inç',
       '16 inç', '16,1 inç', '12,3 inç', '14,1 inç', '18 inç', '18,4 inç',
       '17 inç', '13,4 inç', '15 inç', '13,5 inç', '11,6 inç'],
      dtype=object)

In [39]:
df["Ekran Boyutu"] = df["Ekran Boyutu"].str.replace(" inç", "").str.replace(",",".").astype(float)

In [40]:
df["Ekran Boyutu"].unique()

array([10. , 15.6, 13.3, 14. , 17.3, 13. , 16. , 16.1, 12.3, 14.1, 18. ,
       18.4, 17. , 13.4, 15. , 13.5, 11.6])

In [41]:
df["İşlemci"].unique()

array(['1000M', '1035G1', '10300H', '1135G7', 'N4020', '1065G7', '1005G1',
       '10110U', '10. Nesil Intel® Core™ i3-10110U işlemci', '10200H',
       '10750H', 'N5030', '10510U', '10210U', 'Celeron N4020', '1165G7',
       '1155G7', '11320H', '11260H', '11370H', '11400H', '5600H',
       '11800H', '11390H', '11600H', '1115G4', nan, '1195G7', '1125G4',
       '12700H', '1255U', '1235U', '1260P', '12500H', '12450H', '12800H',
       '12900HK', '12650H', '12900H', '1215U', '1240P', '13980HX',
       '13900HX', '13500H', '6800H', '13700H', '13620H', '13650HX',
       '13500HX', '13900H', '13700HX', '3700U', '3250U', 'AMD Ryzen 5',
       'N4120', '5800H', 'T5600', '5500U', '5625U', '5825U', '5300U',
       '5700U', '5675U', '6800HS', '6600H', '5257U', '1035G16', '7735HS',
       '7940HS', '7320U', '7520U', '7530U', '7Y57', '7Y75', '8565U',
       '9880H', '9300H', 'Apple M2', 'Apple M2 Max', 'Apple M2 Pro',
       '5900HX', '4600H', '7730U', 'AMD R7-5700U', 'Apple M1', 'N4150',
       '

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Bellek Hızı              888 non-null    object 
 1   Cihaz Ağırlığı           994 non-null    float64
 2   Ekran Boyutu             994 non-null    float64
 3   Ekran Kartı Bellek Tipi  884 non-null    object 
 4   Ekran Kartı Hafızası     994 non-null    object 
 5   Ekran Kartı Tipi         955 non-null    object 
 6   Ekran Panel Tipi         994 non-null    object 
 7   İşlemci Nesli            946 non-null    object 
 8   İşlemci                  979 non-null    object 
 9   İşletim Sistemi          994 non-null    object 
 10  Kart Okuyucu             864 non-null    object 
 11  Aydınlatma               994 non-null    int64  
 12  Maksimum İşlemci Hızı    950 non-null    object 
 13  Max Ekran Çözünürlüğü    988 non-null    object 
 14  Parmak İzi Okuyucu       8

In [43]:
df["Ürün Modeli"].unique()

array(['Notebook', 'Oyun Bilgisayarları', 'İkisi Bir Arada', 'Ultrabook'],
      dtype=object)

In [44]:
df["Parmak İzi Okuyucu"].unique()

array([nan, 'Yok', 'Var'], dtype=object)

In [45]:
df["Parmak İzi Okuyucu"].fillna(df["Parmak İzi Okuyucu"].mode()[0],inplace = True)

In [46]:
df["Parmak İzi Okuyucu"].unique()

array(['Yok', 'Var'], dtype=object)

In [47]:
df["Parmak İzi Okuyucu"] = df["Parmak İzi Okuyucu"].replace({
    "Yok" : 0 ,
    "Var" : 1
}).astype(int)

In [48]:
df["Parmak İzi Okuyucu"].unique()

array([0, 1])

In [49]:
df["Max Ekran Çözünürlüğü"].unique()

array([nan, '1920 x 1080', '1366 x 768', '1921 x 1080', '1920 x 1200',
       '2560 x 1440', '1924 x 1080', '1933 x 1080', '1926 x 1080',
       '1920 x 1280', '3840 x 2400', '3840 x 2160', '2560 x 1600',
       '2520 x 1680', '2880 x 1800', '3072 x 1920', '1922 x 1080',
       '2880 x 1864', '3456 x 2234', '3024 x 1964', '2880 x 1620'],
      dtype=object)

In [50]:
df["Max Ekran Çözünürlüğü"] = df["Max Ekran Çözünürlüğü"].fillna(df["Max Ekran Çözünürlüğü"].mode()[0])

In [51]:
df["Max Ekran Çözünürlüğü"].unique()

array(['1920 x 1080', '1366 x 768', '1921 x 1080', '1920 x 1200',
       '2560 x 1440', '1924 x 1080', '1933 x 1080', '1926 x 1080',
       '1920 x 1280', '3840 x 2400', '3840 x 2160', '2560 x 1600',
       '2520 x 1680', '2880 x 1800', '3072 x 1920', '1922 x 1080',
       '2880 x 1864', '3456 x 2234', '3024 x 1964', '2880 x 1620'],
      dtype=object)

In [52]:
# 192 ile başlayan ve toplam 4 haneli olan sayıları 1920 ile değiştir
df['Max Ekran Çözünürlüğü'] = df['Max Ekran Çözünürlüğü'].str.replace(r'192\d x 1080', '1920 x 1080', regex=True)
df['Max Ekran Çözünürlüğü'] = df['Max Ekran Çözünürlüğü'].str.replace(r'1933 x 1080', '1920 x 1080', regex=True)

In [53]:
df["Max Ekran Çözünürlüğü"].unique()

array(['1920 x 1080', '1366 x 768', '1920 x 1200', '2560 x 1440',
       '1920 x 1280', '3840 x 2400', '3840 x 2160', '2560 x 1600',
       '2520 x 1680', '2880 x 1800', '3072 x 1920', '2880 x 1864',
       '3456 x 2234', '3024 x 1964', '2880 x 1620'], dtype=object)

In [54]:
def calculate_pixels(res):
    if pd.isna(res):
        return np.nan
    try:
        # 'x' işaretine göre ayır ve iki sayıyı çarp
        parts = str(res).lower().split('x')
        width = int(parts[0].strip())
        height = int(parts[1].strip())
        
        # Hatalı girişleri (1921, 1922 vb.) 1920'ye yuvarla
        if 1910 <= width <= 1940: width = 1920
        
        return width * height
    except:
        return np.nan

df['Toplam_Piksel'] = df['Max Ekran Çözünürlüğü'].apply(calculate_pixels)

In [55]:
df["Toplam_Piksel"].unique()

array([2073600, 1049088, 2304000, 3686400, 2457600, 9216000, 8294400,
       4096000, 4233600, 5184000, 5898240, 5368320, 7720704, 5939136,
       4665600])

In [56]:
df["Maksimum İşlemci Hızı"].unique()

array(['1,05 GHz', '3,6 GHz', '4,5 GHz', '2,4 GHz', '2,8 GHz', '3,9 GHz',
       '3,4 GHz', '4,1 GHz', '2,1 GHz', '4,2 GHz', '5 GHz', '3,1 GHz',
       '4,9 GHz', '3,5 GHz', '1,1 GHz', '4,7 GHz', '4,4 GHz', '4,8 GHz',
       '4,6 GHz', '2,3 GHz', '2,2 GHz', '3 GHz', '2,5 GHz', '1,2 GHz',
       '3,7 GHz', '3,2 GHz', '4,3 GHz', '5,6 GHz', '5,4 GHz', '5,5 Ghz',
       '4 GHz', '2,6 GHz', '4,0 GHz', '3,8 GHz', '5,2 GHz', nan, '2 GHz',
       '1,8 GHz'], dtype=object)

In [57]:
df["Maksimum İşlemci Hızı"].fillna(df["Maksimum İşlemci Hızı"].mode()[0], inplace = True)

In [58]:
df["Maksimum İşlemci Hızı"] = df["Maksimum İşlemci Hızı"].str.replace(" GHz","")
df["Maksimum İşlemci Hızı"] = df["Maksimum İşlemci Hızı"].str.replace(" Ghz","")
df["Maksimum İşlemci Hızı"] = df["Maksimum İşlemci Hızı"].str.replace(",",".")

In [59]:
df["Maksimum İşlemci Hızı"] = df["Maksimum İşlemci Hızı"].astype(float)

In [60]:
df["Maksimum İşlemci Hızı"].unique()

array([1.05, 3.6 , 4.5 , 2.4 , 2.8 , 3.9 , 3.4 , 4.1 , 2.1 , 4.2 , 5.  ,
       3.1 , 4.9 , 3.5 , 1.1 , 4.7 , 4.4 , 4.8 , 4.6 , 2.3 , 2.2 , 3.  ,
       2.5 , 1.2 , 3.7 , 3.2 , 4.3 , 5.6 , 5.4 , 5.5 , 4.  , 2.6 , 3.8 ,
       5.2 , 2.  , 1.8 ])

In [61]:
df["Kart Okuyucu"].unique()

array([nan, 'Var', 'Yok'], dtype=object)

In [62]:
df["Kart Okuyucu"] = df["Kart Okuyucu"].fillna(df["Kart Okuyucu"].mode()[0])

In [63]:
df["Kart Okuyucu"] = df["Kart Okuyucu"].replace({
    "Yok" : 0 , 
    "Var" : 1
}).astype(int)

In [64]:
df["Kart Okuyucu"].unique()

array([1, 0])

In [65]:
df["İşletim Sistemi"].unique()

array(['Android', 'Windows 10 Home', 'Yok (Free Dos)', 'Windows 11 Pro',
       'Windows 11 Home', 'Windows 10 Pro', 'Ubuntu', 'macOS',
       'Chrome OS'], dtype=object)

In [66]:
df["İşletim Sistemi"] = df["İşletim Sistemi"].str.replace("Yok (Free Dos)" , "Free Dos")

In [67]:
df["İşletim Sistemi"].unique()

array(['Android', 'Windows 10 Home', 'Free Dos', 'Windows 11 Pro',
       'Windows 11 Home', 'Windows 10 Pro', 'Ubuntu', 'macOS',
       'Chrome OS'], dtype=object)

In [68]:
df.isnull().sum()

Bellek Hızı                106
Cihaz Ağırlığı               0
Ekran Boyutu                 0
Ekran Kartı Bellek Tipi    110
Ekran Kartı Hafızası         0
Ekran Kartı Tipi            39
Ekran Panel Tipi             0
İşlemci Nesli               48
İşlemci                     15
İşletim Sistemi              0
Kart Okuyucu                 0
Aydınlatma                   0
Maksimum İşlemci Hızı        0
Max Ekran Çözünürlüğü        0
Parmak İzi Okuyucu           0
Ram (Sistem Belleği)         0
SSD Kapasitesi               0
Ürün Modeli                  0
Fiyat                        0
Toplam_Piksel                0
dtype: int64

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Bellek Hızı              888 non-null    object 
 1   Cihaz Ağırlığı           994 non-null    float64
 2   Ekran Boyutu             994 non-null    float64
 3   Ekran Kartı Bellek Tipi  884 non-null    object 
 4   Ekran Kartı Hafızası     994 non-null    object 
 5   Ekran Kartı Tipi         955 non-null    object 
 6   Ekran Panel Tipi         994 non-null    object 
 7   İşlemci Nesli            946 non-null    object 
 8   İşlemci                  979 non-null    object 
 9   İşletim Sistemi          994 non-null    object 
 10  Kart Okuyucu             994 non-null    int64  
 11  Aydınlatma               994 non-null    int64  
 12  Maksimum İşlemci Hızı    994 non-null    float64
 13  Max Ekran Çözünürlüğü    994 non-null    object 
 14  Parmak İzi Okuyucu       9

In [70]:
df.drop("Max Ekran Çözünürlüğü", axis = 1, inplace = True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Bellek Hızı              888 non-null    object 
 1   Cihaz Ağırlığı           994 non-null    float64
 2   Ekran Boyutu             994 non-null    float64
 3   Ekran Kartı Bellek Tipi  884 non-null    object 
 4   Ekran Kartı Hafızası     994 non-null    object 
 5   Ekran Kartı Tipi         955 non-null    object 
 6   Ekran Panel Tipi         994 non-null    object 
 7   İşlemci Nesli            946 non-null    object 
 8   İşlemci                  979 non-null    object 
 9   İşletim Sistemi          994 non-null    object 
 10  Kart Okuyucu             994 non-null    int64  
 11  Aydınlatma               994 non-null    int64  
 12  Maksimum İşlemci Hızı    994 non-null    float64
 13  Parmak İzi Okuyucu       994 non-null    int64  
 14  Ram (Sistem Belleği)     9

In [72]:
df["Ürün Modeli"].unique()

array(['Notebook', 'Oyun Bilgisayarları', 'İkisi Bir Arada', 'Ultrabook'],
      dtype=object)

In [73]:
df["İşlemci Nesli"].unique()

array(['1.Nesil', '10. Nesil', '10.Nesil', 'Yok', '11.Nesil', '12.Nesil',
       '13.Nesil', '3.Nesil', '4.Nesil', '5.Nesil', '6.Nesil', '7.Nesil',
       '8.Nesil', '9.Nesil', 'Apple M2', 'Apple M2 Max', 'Apple M2 Pro',
       'İntel N Serisi', 'M2', 'M2 Max', 'M2 Pro', 'Ryzen', nan],
      dtype=object)

In [74]:
df["İşlemci Nesli"] = df["İşlemci Nesli"].replace("Yok","0")

In [75]:
df["İşlemci Nesli"].unique()

array(['1.Nesil', '10. Nesil', '10.Nesil', '0', '11.Nesil', '12.Nesil',
       '13.Nesil', '3.Nesil', '4.Nesil', '5.Nesil', '6.Nesil', '7.Nesil',
       '8.Nesil', '9.Nesil', 'Apple M2', 'Apple M2 Max', 'Apple M2 Pro',
       'İntel N Serisi', 'M2', 'M2 Max', 'M2 Pro', 'Ryzen', nan],
      dtype=object)

In [76]:
df["İşlemci Nesli"].fillna(df["İşlemci Nesli"].mode()[0], inplace = True)

In [77]:
df["İşlemci Nesli"].unique()

array(['1.Nesil', '10. Nesil', '10.Nesil', '0', '11.Nesil', '12.Nesil',
       '13.Nesil', '3.Nesil', '4.Nesil', '5.Nesil', '6.Nesil', '7.Nesil',
       '8.Nesil', '9.Nesil', 'Apple M2', 'Apple M2 Max', 'Apple M2 Pro',
       'İntel N Serisi', 'M2', 'M2 Max', 'M2 Pro', 'Ryzen'], dtype=object)

In [78]:
# Bir eşleme sözlüğü (mapping) oluşturuyoruz
nesil_mapping = {
    '13.Nesil': 13, '12.Nesil': 12, '11.Nesil': 11, '10.Nesil': 10, '10. Nesil': 10,
    '9.Nesil': 9, '8.Nesil': 8, '7.Nesil': 7, '6.Nesil': 6, '5.Nesil': 5,
    '4.Nesil': 4, '3.Nesil': 3, '1.Nesil': 1, '0': 0,
    # Apple ve Diğerleri için mantıksal karşılıklar
    'Apple M2': 13, 'M2': 13, 'M2 Pro': 13.5, 'M2 Max': 14, 
    'Apple M2 Pro': 13.5, 'Apple M2 Max': 14,
    'Ryzen': 10,  # Belirsiz Ryzen'leri orta bir nesil kabul edebiliriz
    'İntel N Serisi': 10 # Genelde 10-11. nesil mimarisidir
}

df['İşlemci Nesli'] = df['İşlemci Nesli'].map(nesil_mapping)

In [79]:
df['İşlemci Nesli'].dtype

dtype('float64')

In [80]:
df["Ekran Panel Tipi"].unique()

array(['IPS', 'LED', 'TN', 'SVA', 'WVA', 'OLED', 'LTPS', 'Mini LED',
       'Liquid Retina Ekran', 'Liquid Retina XDR'], dtype=object)

In [81]:
df["Ekran Kartı Tipi"].unique()

array([nan, 'Harici Ekran Kartı', 'Yüksek Seviye Harici Ekran Kartı',
       'Dahili Ekran Kartı'], dtype=object)

In [82]:
df["Ekran Kartı Tipi"] = df["Ekran Kartı Tipi"].fillna(df["Ekran Kartı Tipi"].mode()[0])

In [83]:
df["Ekran Kartı Tipi"] = df["Ekran Kartı Tipi"].replace({
    "Dahili Ekran Kartı" : 1 ,
    "Harici Ekran Kartı" : 2 , 
    "Yüksek Seviye Harici Ekran Kartı" : 3
}).astype(int)

In [84]:
df["Ekran Kartı Tipi"].unique()

array([1, 2, 3])

In [85]:
df["Ekran Kartı Hafızası"].unique()

array(['1', '2', '4', '8', '0', '6', '12', '16'], dtype=object)

In [86]:
df["Ekran Kartı Hafızası"] = df["Ekran Kartı Hafızası"].astype(int) 

In [87]:
df["Ekran Kartı Bellek Tipi"].unique()

array([nan, 'GDDR4', 'GDDR5', 'GDDR6', 'Onboard', 'DDR3', 'DDR5',
       'GDDR6X'], dtype=object)

In [88]:
df["Ekran Kartı Bellek Tipi"].fillna(df["Ekran Kartı Bellek Tipi"].mode()[0] , inplace = True)

In [89]:
df["Ekran Kartı Bellek Tipi"].unique()

array(['Onboard', 'GDDR4', 'GDDR5', 'GDDR6', 'DDR3', 'DDR5', 'GDDR6X'],
      dtype=object)

In [90]:
vram_tipi_mapping = {
    'Onboard': 0,      # Kendi belleği yok, en düşük
    'DDR3': 1,         # Çok eski teknoloji
    'GDDR4': 2,        # Eski
    'GDDR5': 3,        # Standart/Eski (Hala yaygın)
    'DDR5': 4,         # Yeni nesil (Daha çok işlemci RAM'i ama bazı GPU'larda var)
    'GDDR6': 5,        # Güncel standart (Yüksek performans)
    'GDDR6X': 6        # En üst seviye (Premium performans)"
}

In [91]:
df["Ekran Kartı Bellek Tipi"] = df["Ekran Kartı Bellek Tipi"].map(vram_tipi_mapping)

In [92]:
df["Ekran Kartı Bellek Tipi"].dtype

dtype('int64')

In [93]:
df["Bellek Hızı"].unique() 

array(['1066 MHz', '3200 MHz', '2933 MHz', nan, '2666 MHz', '2400 MHz',
       '3000 MHz', '3733 MHz', '4267 MHz', '4800 MHz', '5200 MHz',
       '4266 MHz', '6400 MHz', '1600 MHz', '5500 MHz', '1866 MHz',
       '2133 MHz'], dtype=object)

In [94]:
df["Bellek Hızı"] = df["Bellek Hızı"].fillna(df["Bellek Hızı"].mode()[0])

In [95]:
df["Bellek Hızı"] = df["Bellek Hızı"].str.replace(" MHz", "")

In [96]:
df["Bellek Hızı"].unique() 

array(['1066', '3200', '2933', '2666', '2400', '3000', '3733', '4267',
       '4800', '5200', '4266', '6400', '1600', '5500', '1866', '2133'],
      dtype=object)

In [97]:
df["Bellek Hızı"] = df["Bellek Hızı"].astype(int)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Bellek Hızı              994 non-null    int64  
 1   Cihaz Ağırlığı           994 non-null    float64
 2   Ekran Boyutu             994 non-null    float64
 3   Ekran Kartı Bellek Tipi  994 non-null    int64  
 4   Ekran Kartı Hafızası     994 non-null    int64  
 5   Ekran Kartı Tipi         994 non-null    int64  
 6   Ekran Panel Tipi         994 non-null    object 
 7   İşlemci Nesli            994 non-null    float64
 8   İşlemci                  979 non-null    object 
 9   İşletim Sistemi          994 non-null    object 
 10  Kart Okuyucu             994 non-null    int64  
 11  Aydınlatma               994 non-null    int64  
 12  Maksimum İşlemci Hızı    994 non-null    float64
 13  Parmak İzi Okuyucu       994 non-null    int64  
 14  Ram (Sistem Belleği)     9

In [99]:
df.isnull().sum()

Bellek Hızı                 0
Cihaz Ağırlığı              0
Ekran Boyutu                0
Ekran Kartı Bellek Tipi     0
Ekran Kartı Hafızası        0
Ekran Kartı Tipi            0
Ekran Panel Tipi            0
İşlemci Nesli               0
İşlemci                    15
İşletim Sistemi             0
Kart Okuyucu                0
Aydınlatma                  0
Maksimum İşlemci Hızı       0
Parmak İzi Okuyucu          0
Ram (Sistem Belleği)        0
SSD Kapasitesi              0
Ürün Modeli                 0
Fiyat                       0
Toplam_Piksel               0
dtype: int64

In [100]:
df["İşlemci"] = df["İşlemci"].fillna(df["İşlemci"].mode()[0])

In [101]:
df.isnull().sum()

Bellek Hızı                0
Cihaz Ağırlığı             0
Ekran Boyutu               0
Ekran Kartı Bellek Tipi    0
Ekran Kartı Hafızası       0
Ekran Kartı Tipi           0
Ekran Panel Tipi           0
İşlemci Nesli              0
İşlemci                    0
İşletim Sistemi            0
Kart Okuyucu               0
Aydınlatma                 0
Maksimum İşlemci Hızı      0
Parmak İzi Okuyucu         0
Ram (Sistem Belleği)       0
SSD Kapasitesi             0
Ürün Modeli                0
Fiyat                      0
Toplam_Piksel              0
dtype: int64

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Bellek Hızı              994 non-null    int64  
 1   Cihaz Ağırlığı           994 non-null    float64
 2   Ekran Boyutu             994 non-null    float64
 3   Ekran Kartı Bellek Tipi  994 non-null    int64  
 4   Ekran Kartı Hafızası     994 non-null    int64  
 5   Ekran Kartı Tipi         994 non-null    int64  
 6   Ekran Panel Tipi         994 non-null    object 
 7   İşlemci Nesli            994 non-null    float64
 8   İşlemci                  994 non-null    object 
 9   İşletim Sistemi          994 non-null    object 
 10  Kart Okuyucu             994 non-null    int64  
 11  Aydınlatma               994 non-null    int64  
 12  Maksimum İşlemci Hızı    994 non-null    float64
 13  Parmak İzi Okuyucu       994 non-null    int64  
 14  Ram (Sistem Belleği)     9

In [103]:
df.describe()

Bellek Hızı  Cihaz Ağırlığı  Ekran Boyutu  Ekran Kartı Bellek Tipi  \
count   994.000000      994.000000    994.000000               994.000000   
mean   3324.957746        1.912978     15.336016                 1.648893   
std     593.487688        0.743026      0.923221                 2.271693   
min    1066.000000        1.000000     10.000000                 0.000000   
25%    3200.000000        1.500000     15.600000                 0.000000   
50%    3200.000000        1.500000     15.600000                 0.000000   
75%    3200.000000        3.000000     15.600000                 5.000000   
max    6400.000000        5.000000     18.400000                 6.000000   

       Ekran Kartı Hafızası  Ekran Kartı Tipi  İşlemci Nesli  Kart Okuyucu  \
count            994.000000        994.000000     994.000000    994.000000   
mean               1.669014          1.538229      10.436620      0.604628   
std                2.800177          0.776705       2.359444      0.489177   
min                0.000000          1.000000       0.000000      0.000000   
25%                0.000000          1.000000      10.000000      0.000000   
50%                0.000000          1.000000      11.000000      1.000000   
75%                4.000000          2.000000      12.000000      1.000000   
max               16.000000          3.000000      14.000000      1.000000   

       Aydınlatma  Maksimum İşlemci Hızı  Parmak İzi Okuyucu  \
count  994.000000             994.000000          994.000000   
mean     0.243461               4.311066            0.195171   
std      0.429387               0.608308            0.396532   
min      0.000000               1.050000            0.000000   
25%      0.000000               4.200000            0.000000   
50%      0.000000               4.400000            0.000000   
75%      0.000000               4.700000            0.000000   
max      1.000000               5.600000            1.000000   

       Ram (Sistem Belleği)  SSD Kapasitesi  Toplam_Piksel  
count            994.000000      994.000000   9.940000e+02  
mean              17.492958      645.720322   2.279563e+06  
std               12.349087      435.145913   1.009301e+06  
min                4.000000        0.000000   1.049088e+06  
25%                8.000000      500.000000   2.073600e+06  
50%               16.000000      512.000000   2.073600e+06  
75%               16.000000     1024.000000   2.073600e+06  
max              128.000000     4096.000000   9.216000e+06

In [104]:
df["Fiyat"].unique()

array(['Çok Yüksek', 'Orta', 'Düşük', 'Çok Düşük', 'Yüksek'], dtype=object)

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Bellek Hızı              994 non-null    int64  
 1   Cihaz Ağırlığı           994 non-null    float64
 2   Ekran Boyutu             994 non-null    float64
 3   Ekran Kartı Bellek Tipi  994 non-null    int64  
 4   Ekran Kartı Hafızası     994 non-null    int64  
 5   Ekran Kartı Tipi         994 non-null    int64  
 6   Ekran Panel Tipi         994 non-null    object 
 7   İşlemci Nesli            994 non-null    float64
 8   İşlemci                  994 non-null    object 
 9   İşletim Sistemi          994 non-null    object 
 10  Kart Okuyucu             994 non-null    int64  
 11  Aydınlatma               994 non-null    int64  
 12  Maksimum İşlemci Hızı    994 non-null    float64
 13  Parmak İzi Okuyucu       994 non-null    int64  
 14  Ram (Sistem Belleği)     9

In [106]:
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [107]:
# Sıralamayı biz belirliyoruz (Küçükten büyüğe)
fiyat_siralamasi = [['Çok Düşük', 'Düşük', 'Orta', 'Yüksek', 'Çok Yüksek']]

encoder = OrdinalEncoder(categories=fiyat_siralamasi)

# Fiyat sütununu dönüştür (0, 1, 2, 3, 4 değerlerini alacaktır)
df['Fiyat'] = encoder.fit_transform(df[['Fiyat']])

In [108]:
X = df.drop("Fiyat", axis = 1)
y = df["Fiyat"]

In [109]:
from sklearn.model_selection import train_test_split 
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size = 0.25, random_state = 15)

In [110]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

# Az seçenekli olanlar (OHE için ideal)
ohe_cols = ["Ekran Panel Tipi", "İşletim Sistemi"]
# Çok seçenekli olanlar (Ordinal için daha güvenli)
ord_cols = ["İşlemci", "Ürün Modeli"]

preprocessor = ColumnTransformer(transformers=[
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False), ohe_cols),
    ('ord', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), ord_cols)
], remainder="passthrough")

# Dönüştürme işlemleri
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [111]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train_transformed)
X_test_scaled = scaler.transform(X_test_transformed)

In [112]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [113]:
rfc = RandomForestClassifier()

In [114]:
rfc.fit(X_train_scaled,y_train)

RandomForestClassifier()

In [115]:
y_pred = rfc.predict(X_test_scaled)

In [116]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.8353413654618473
[[ 16   2   0   0   0]
 [  2 102   4   0   0]
 [  0  14  47   4   0]
 [  0   1  11  23   0]
 [  0   0   2   1  20]]
              precision    recall  f1-score   support

         0.0       0.89      0.89      0.89        18
         1.0       0.86      0.94      0.90       108
         2.0       0.73      0.72      0.73        65
         3.0       0.82      0.66      0.73        35
         4.0       1.00      0.87      0.93        23

    accuracy                           0.84       249
   macro avg       0.86      0.82      0.84       249
weighted avg       0.84      0.84      0.83       249



In [117]:
# hyperparameter tuning 
params = {
    "n_estimators" : [100,200,500,1000],
    "max_depth" : [5,8,10,15,None],
    "max_features" : ["sqrt", "log2", 5,6,7,8],
    "min_samples_split" : [2,8,15,20]
}

In [118]:
from sklearn.model_selection import RandomizedSearchCV , GridSearchCV

In [119]:
randomcv = RandomizedSearchCV(estimator = rfc , param_distributions = params , cv=5)

In [120]:
randomcv.fit(X_train_scaled , y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'max_depth': [5, 8, 10, 15, None],
                                        'max_features': ['sqrt', 'log2', 5, 6,
                                                         7, 8],
                                        'min_samples_split': [2, 8, 15, 20],
                                        'n_estimators': [100, 200, 500, 1000]})

In [121]:
randomcv.best_params_

{'n_estimators': 500,
 'min_samples_split': 2,
 'max_features': 6,
 'max_depth': 15}

In [122]:
print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.8353413654618473
[[ 16   2   0   0   0]
 [  2 102   4   0   0]
 [  0  14  47   4   0]
 [  0   1  11  23   0]
 [  0   0   2   1  20]]
              precision    recall  f1-score   support

         0.0       0.89      0.89      0.89        18
         1.0       0.86      0.94      0.90       108
         2.0       0.73      0.72      0.73        65
         3.0       0.82      0.66      0.73        35
         4.0       1.00      0.87      0.93        23

    accuracy                           0.84       249
   macro avg       0.86      0.82      0.84       249
weighted avg       0.84      0.84      0.83       249



In [123]:
from sklearn.svm import SVC 

In [124]:
svc = SVC()

In [125]:
svc.fit(X_train_scaled, y_train)

SVC()

In [126]:
y_pred = svc.predict(X_test_scaled)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.7269076305220884
[[  8  10   0   0   0]
 [  2 103   3   0   0]
 [  0  26  35   4   0]
 [  0   6   9  13   7]
 [  0   0   0   1  22]]
              precision    recall  f1-score   support

         0.0       0.80      0.44      0.57        18
         1.0       0.71      0.95      0.81       108
         2.0       0.74      0.54      0.62        65
         3.0       0.72      0.37      0.49        35
         4.0       0.76      0.96      0.85        23

    accuracy                           0.73       249
   macro avg       0.75      0.65      0.67       249
weighted avg       0.73      0.73      0.70       249



In [127]:
# hyperparameter tuning for svc 
svc_params = {
    "C" : [0.1,1,10,100,1000],
    "kernel" : ["linear", "poly", "rbf" , "sigmoid"],
    "degree" : [2,3,4,5,7,8],
    "gamma" : ["scale", "auto"]
}

In [128]:
gridcv = GridSearchCV(estimator = SVC() , param_grid = svc_params , cv=3 , n_jobs = -1 , scoring = "accuracy" )

In [129]:
gridcv.fit(X_train_scaled,y_train)

GridSearchCV(cv=3, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'degree': [2, 3, 4, 5, 7, 8],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='accuracy')

In [130]:
gridcv.best_params_

{'C': 10, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}

In [131]:
y_pred = gridcv.predict(X_test_scaled)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.751004016064257
[[14  4  0  0  0]
 [ 7 95  6  0  0]
 [ 0 24 36  4  1]
 [ 0  2  9 21  3]
 [ 0  0  1  1 21]]
              precision    recall  f1-score   support

         0.0       0.67      0.78      0.72        18
         1.0       0.76      0.88      0.82       108
         2.0       0.69      0.55      0.62        65
         3.0       0.81      0.60      0.69        35
         4.0       0.84      0.91      0.88        23

    accuracy                           0.75       249
   macro avg       0.75      0.74      0.74       249
weighted avg       0.75      0.75      0.74       249



In [132]:
from sklearn.tree import DecisionTreeClassifier

In [133]:
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [134]:
y_pred = dt_clf.predict(X_test_scaled)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.7791164658634538
[[14  4  0  0  0]
 [ 6 91 10  0  1]
 [ 0 14 46  5  0]
 [ 0  0  9 23  3]
 [ 0  0  2  1 20]]
              precision    recall  f1-score   support

         0.0       0.70      0.78      0.74        18
         1.0       0.83      0.84      0.84       108
         2.0       0.69      0.71      0.70        65
         3.0       0.79      0.66      0.72        35
         4.0       0.83      0.87      0.85        23

    accuracy                           0.78       249
   macro avg       0.77      0.77      0.77       249
weighted avg       0.78      0.78      0.78       249



In [135]:
dt_params = {
    "criterion" : ["gini", "entropy" , "log_loss"],
    "splitter" : ["best","random"],
    "max_depth" : [1,2,3,4,5,15,None],
    "max_features" : ["sqrt", "log2" , None]
}

In [136]:
gridcv = GridSearchCV(estimator = DecisionTreeClassifier() , param_grid = dt_params , cv=3 , n_jobs = -1 , scoring = "accuracy" )

In [137]:
gridcv.fit(X_train_scaled , y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [1, 2, 3, 4, 5, 15, None],
                         'max_features': ['sqrt', 'log2', None],
                         'splitter': ['best', 'random']},
             scoring='accuracy')

In [138]:
y_pred = gridcv.predict(X_test_scaled)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.7550200803212851
[[13  5  0  0  0]
 [10 93  5  0  0]
 [ 1 20 39  3  2]
 [ 1  2  7 21  4]
 [ 0  0  0  1 22]]
              precision    recall  f1-score   support

         0.0       0.52      0.72      0.60        18
         1.0       0.78      0.86      0.82       108
         2.0       0.76      0.60      0.67        65
         3.0       0.84      0.60      0.70        35
         4.0       0.79      0.96      0.86        23

    accuracy                           0.76       249
   macro avg       0.74      0.75      0.73       249
weighted avg       0.76      0.76      0.75       249



In [139]:
from sklearn.ensemble import AdaBoostClassifier , GradientBoostingClassifier 

In [140]:
ada = AdaBoostClassifier()
ada.fit(X_train_scaled, y_train)

AdaBoostClassifier()

In [141]:
y_pred = ada.predict(X_test_scaled)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.6706827309236948
[[12  6  0  0  0]
 [ 6 97  4  1  0]
 [ 0 34 25  6  0]
 [ 0  3  7 22  3]
 [ 0  0  1 11 11]]
              precision    recall  f1-score   support

         0.0       0.67      0.67      0.67        18
         1.0       0.69      0.90      0.78       108
         2.0       0.68      0.38      0.49        65
         3.0       0.55      0.63      0.59        35
         4.0       0.79      0.48      0.59        23

    accuracy                           0.67       249
   macro avg       0.67      0.61      0.62       249
weighted avg       0.67      0.67      0.65       249



In [142]:
adaboost_param = {
    "n_estimators" : [50,70,100,120,150,200],
    "learning_rate" : [0.001,0.01,0.1,1,10]
}

In [143]:
gridcv = GridSearchCV(estimator = AdaBoostClassifier() ,
                      param_grid = adaboost_param , cv = 3 ,
                      verbose = 1 , n_jobs = -1)

In [144]:
gridcv.fit(X_train_scaled,y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits


GridSearchCV(cv=3, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 1, 10],
                         'n_estimators': [50, 70, 100, 120, 150, 200]},
             verbose=1)

In [145]:
gridcv.best_params_

{'learning_rate': 1, 'n_estimators': 120}

In [146]:
y_pred = gridcv.predict(X_test_scaled)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.6907630522088354
[[12  6  0  0  0]
 [ 6 91 10  1  0]
 [ 0 27 31  6  1]
 [ 0  2  7 25  1]
 [ 0  0  3  7 13]]
              precision    recall  f1-score   support

         0.0       0.67      0.67      0.67        18
         1.0       0.72      0.84      0.78       108
         2.0       0.61      0.48      0.53        65
         3.0       0.64      0.71      0.68        35
         4.0       0.87      0.57      0.68        23

    accuracy                           0.69       249
   macro avg       0.70      0.65      0.67       249
weighted avg       0.69      0.69      0.68       249



In [147]:
gbc = GradientBoostingClassifier()

In [148]:
gbc.fit(X_train_scaled , y_train)

GradientBoostingClassifier()

In [149]:
y_pred = gbc.predict(X_test_scaled)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.8353413654618473
[[ 16   2   0   0   0]
 [  2 102   4   0   0]
 [  0  16  44   5   0]
 [  0   0  11  24   0]
 [  0   0   0   1  22]]
              precision    recall  f1-score   support

         0.0       0.89      0.89      0.89        18
         1.0       0.85      0.94      0.89       108
         2.0       0.75      0.68      0.71        65
         3.0       0.80      0.69      0.74        35
         4.0       1.00      0.96      0.98        23

    accuracy                           0.84       249
   macro avg       0.86      0.83      0.84       249
weighted avg       0.83      0.84      0.83       249



In [150]:
gbc_params = {
    "loss" : ["log_loss", "exponential"],
    "learning_rate" : [0.01,0.05,0.1,1.0],
    "n_estimators" : [100,120,150,200],
    "criterion" : ["friedman_mse" , "squared_error"],
    "max_depth" : [3,4,5],
    "subsample" : [0.8,1.0]
}

In [151]:
gridcv = GridSearchCV(estimator = gbc , param_grid = gbc_params , cv=3 , n_jobs = -1 , scoring = "accuracy" )

In [152]:
gridcv.fit(X_train_scaled,y_train)

GridSearchCV(cv=3, estimator=GradientBoostingClassifier(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'learning_rate': [0.01, 0.05, 0.1, 1.0],
                         'loss': ['log_loss', 'exponential'],
                         'max_depth': [3, 4, 5],
                         'n_estimators': [100, 120, 150, 200],
                         'subsample': [0.8, 1.0]},
             scoring='accuracy')

In [153]:
gridcv.best_params_

{'criterion': 'friedman_mse',
 'learning_rate': 0.05,
 'loss': 'log_loss',
 'max_depth': 5,
 'n_estimators': 120,
 'subsample': 1.0}

In [154]:
y_pred = gridcv.predict(X_test_scaled)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  0.8473895582329317
[[ 15   3   0   0   0]
 [  2 103   3   0   0]
 [  0  15  45   5   0]
 [  0   1   8  26   0]
 [  0   0   0   1  22]]
              precision    recall  f1-score   support

         0.0       0.88      0.83      0.86        18
         1.0       0.84      0.95      0.90       108
         2.0       0.80      0.69      0.74        65
         3.0       0.81      0.74      0.78        35
         4.0       1.00      0.96      0.98        23

    accuracy                           0.85       249
   macro avg       0.87      0.84      0.85       249
weighted avg       0.85      0.85      0.84       249

